from pydantic import BaseModel, Field
from typing import Any, Dict, Literal, Optional, List, Union

EventTypes = Literal[
    "START",
    "FLIGHT_TAKEOFF",
    "FLIGHT_LAND",
    "HOTEL_CHECKIN",
    "HOTEL_CHECKOUT",
    "CAR_PICKUP",
    "CAR_DROPOFF",
    "DINING",
    "ACTIVITY",
    "COMMUTE",
    "OTHER",
    "END"
]

class Coordinates(BaseModel):
    latitude: float = Field(ge=-90, le=90, description="Latitude of the location. Must be a valid latitude between -90 and 90 degrees returned from any of the tools.")
    longitude: float = Field(ge=-180, le=180, description="Longitude of the location. Must be a valid longitude between -180 and 180 degrees returned from any of the tools.")

# Trip Start Event Details
class StartEventDetails(BaseModel):
    number_of_days: int = Field(description="Total number of days in the trip. Calculate this based on the user's input for start date and end date, both inclusive.")
    start_date: str = Field(description="Start date of the trip as per origin local time in format YYYY-MM-DD. Based on user's chosen start date.")
    end_date: str = Field(description="End date of the trip as per destination local time in format YYYY-MM-DD. Based on user's chosen end date.")
    journey: List[str] = Field(description="List of all destinations in the trip in order of travel. Use get_optimal_route tool if needed for this. For single destination just place that destination here. This list will not have the origin at first or last index, just the destinations in between.")
    trip_title: str = Field(description="A small title for the trip. Must be generated by you based on the user's input for the trip and the results from the tools you have called till now.")
    trip_cost_estimate: float = Field(description="Estimated cost for the entire trip in USD. This is before planing the itinerary, so just use the budget from the user input and use search_web to get an estimated cost for the trip.")

# Itinerary Event Details

# Flight Details
class LayoverDetails(BaseModel):
    airport_code: str = Field(description="Layover airport code. Must be a valid airport code returned from search_flights tool.")
    airport_name: str = Field(description="Layover airport name. Must be a valid airport name returned from search_flights tool.")
    airport_coordinates: Coordinates = Field(description="Layover airport coordinates. Must be a valid coordinates returned from search_flights tool or from get_coordinates tool.")
    durationMinutes: float = Field(description="Duration of layover in minutes. Must be a valid duration in minutes returned from search_flights tool.")

class FlightTakeoffEventDetails(BaseModel):
    airline: str = Field(description="Airline name. Must be a valid airline name returned from search_flights tool.")
    airline_logo_url: Optional[str] = Field(default=None, description="Logo URL of the airline. Must be a valid logo URL returned from search_flights tool.")
    flight_number: str = Field(description="Flight number. Must be a valid flight number returned from search_flights tool.")
    departure_airport_name: str = Field(description="Departure airport name. Must be a valid airport name returned from search_flights tool.")
    departure_airport_code: str = Field(description="Departure airport code. Must be a valid airport code returned from search_flights tool.")
    departure_coordinates: Coordinates = Field(description="Coordinates of the departure airport. Must be a valid coordinates returned from search_flights tool or from get_coordinates tool.")
    departure_time: str = Field(description="Departure time as per local time of the departure airport in format YYYY-MM-DDTHH:MM:SS. Must be a valid departure time returned from search_flights tool or generated by you based on the departure_time returned from search_flights tool.")
    durationMinutes: float = Field(description="Duration of the flight in minutes. Must be a valid duration in minutes returned from search_flights tool.")
    cost: float = Field(description="Cost of the flight in USD. Must be a valid price in USD returned from search_flights tool. Cost returned is for the number of travellers you searched for in the search_flights tool.")
    takeoff_tips: str = Field(description="Tips for the flight takeoff. Must be generated by you based on the airline name and flight number and the departure airport name and code and the departure time and any results you get from search_web tool. Or generated by you based on the departure_time returned from search_flights tool.")
    layovers: List[LayoverDetails] = Field(default_factory=list, description="List of layovers, if any. Must be a valid list of layovers returned from search_flights tool.")
    booking_token: str = Field(description="Flight booking token. Must be a valid booking token returned from search_flights tool.")

class FlightLandEventDetails(BaseModel):
    airline: str = Field(description="Airline name. Must be a valid airline name returned from search_flights tool.")
    airline_logo_url: Optional[str] = Field(default=None, description="Logo URL of the airline. Must be a valid logo URL returned from search_flights tool.")
    flight_number: str = Field(description="Flight number. Must be a valid flight number returned from search_flights tool.")
    arrival_airport_name: str = Field(description="Arrival airport name. Must be a valid airport name returned from search_flights tool.")
    arrival_airport_code: str = Field(description="Arrival airport code. Must be a valid airport code returned from search_flights tool.")
    arrival_coordinates: Coordinates = Field(description="Coordinates of the arrival airport. Must be a valid coordinates returned from search_flights tool or from get_coordinates tool.")
    arrival_time: str = Field(description="Arrival time as per local time of the arrival airport in format YYYY-MM-DDTHH:MM:SS. Must be a valid arrival time returned from search_flights tool or generated by you based on the arrival_time returned from search_flights tool.")
    landing_tips: str = Field(description="Tips for the flight landing. Must be generated by you based on the airline name and flight number and the arrival airport name and code and the arrival time and any results you get from search_web tool. Or generated by you based on the arrival_time returned from search_flights tool.")

class HotelCheckinEventDetails(BaseModel):
    hotel_name: str = Field(description="Name of the hotel. Must be a valid property name returned from search_hotels tool.")
    hotel_id: str = Field(description="Property ID. Must be a valid property ID returned from search_hotels tool.")
    address: str = Field(description="Address of the hotel. Must be a valid address returned from search_hotels tool.")
    hotel_coordinates: Coordinates = Field(description="Coordinates of the hotel. Must be a valid coordinates returned from search_hotels tool or from get_coordinates tool.")
    checkin_time: str = Field(description="Check-in time in format YYYY-MM-DDTHH:MM:SS. Must be decided by you based on the check_in_rules returned from search_hotels tool.")
    checkin_rules: str = Field(description="Check-in rules of the hotel. Must be a valid check-in rules returned from search_hotels tool.")
    nbRooms: int = Field(description="Number of rooms to be booked in the hotel. Must be a valid number of rooms returned from search_hotels tool.")
    nbAdults: int = Field(description="Number of adults staying in the hotel. Must be a valid number of adults returned from search_hotels tool.")
    nbChildren: int = Field(description="Number of children staying in the hotel. Must be a valid number of children returned from search_hotels tool.")
    stayLengthInDays: int = Field(description="Stay length in days. Must be a valid stay length in days returned from search_hotels tool.")
    cost: float = Field(description="Cost of the hotel in USD. Must be a valid cost estimate based on the price_for_stay_in_usd returned from search_hotels tool.")
    checkin_tips: str = Field(description="Tips for the hotel check in. Must be generated by you based on the hotel name and type of the hotel and the location and any results you get from search_web tool.")
    starRating: int = Field(description="Star rating of the hotel. Must be a valid star rating returned from search_hotels tool.")
    rating: Optional[float] = Field(default=0.0, description="Rating of the hotel. Must be a valid rating returned from search_hotels tool.")
    reviews_summary: Optional[str] = Field(default="", description="Reviews summary of the hotel. Must be a valid reviews summary returned from search_hotels tool or generated by you based on the hotel name and type of the hotel and the location and any results you get from search_web tool.")

class HotelCheckoutEventDetails(BaseModel):
    hotel_name: str = Field(description="Name of the hotel. Must be a valid property name returned from search_hotels tool.")
    hotel_id: str = Field(description="Property ID. Must be a valid property ID returned from search_hotels tool.")
    address: str = Field(description="Address of the hotel. Must be a valid address returned from search_hotels tool.")
    hotel_coordinates: Coordinates = Field(description="Coordinates of the hotel. Must be a valid coordinates returned from search_hotels tool or from get_coordinates tool.")
    checkout_time: str = Field(description="Checkout time in format YYYY-MM-DDTHH:MM:SS. Must be decided by you based on the check_out_rules returned from search_hotels tool.")
    checkout_rules: str = Field(description="Check-out rules of the hotel. Must be a valid check-out rules returned from search_hotels tool.")
    checkout_tips: str = Field(description="Tips for the hotel check out. Must be generated by you based on the hotel name and type of the hotel and the location and any results you get from search_web tool.")

# Rental Car Details
class VehicleDetails(BaseModel):
    vehicle_id: str = Field(description="Vehicle id. Must be a valid vehicle ID returned from search_car_rental tool.")
    vehicle_name: str = Field(description="Model/Name of the vehicle. Must be a valid vehicle name returned from search_car_rental tool.")
    vehicle_image_url: Optional[str] = Field(default=None, description="Image URL of the vehicle. Must be a valid vehicle image URL returned from search_car_rental tool.")
    vehicle_transmission: str = Field(description="Transmission type (e.g. automatic, manual). Must be a valid transmission type returned from search_car_rental tool.")
    vehicle_seats: int = Field(description="Number of seats. Must be a valid number of seats returned from search_car_rental tool.")
    vehicle_doors: int = Field(description="Number of doors. Must be a valid number of doors returned from search_car_rental tool.")
    mileage: str = Field(description="Mileage limits or text. Must be a valid mileage limits or text returned from search_car_rental tool.")
    fuel_type: str = Field(description="Fuel type (e.g. Petrol, Diesel, Electric). Must be a valid fuel type returned from search_car_rental tool.")
    free_cancellation: bool = Field(description="Is free cancellation available. Must be a valid free cancellation available returned from search_car_rental tool.")
    airbags: bool = Field(description="Are airbags included. Must be a valid airbags included returned from search_car_rental tool.")
    group: str = Field(description="Vehicle group classifications. Must be a valid vehicle group classifications returned from search_car_rental tool.")

class CarPickupEventDetails(BaseModel):
    rental_company_name: str = Field(description="Name of the rental car company. Must be a valid supplier name returned from search_car_rental tool.")
    rental_company_logo_url: Optional[str] = Field(default=None, description="Logo URL of the rental car company. Must be a valid supplier logo URL returned from search_car_rental tool.")
    pickup_instructions: str = Field(description="Instructions for pickup. Must be a valid pickup instructions returned from search_car_rental tool.")
    pickup_location_id: str = Field(description="Pickup location ID. Must be a valid pickup location ID returned from search_car_rental tool.")
    pickup_location_name: str = Field(description="Pickup location name. Must be a valid pickup location name returned from search_car_rental tool.")
    pickup_location_address: str = Field(description="Pickup location address. Must be a valid pickup location address returned from search_car_rental tool.")
    pickup_location_coordinates: Coordinates = Field(description="Coordinates of the pickup location. Must be a valid pickup location coordinates returned from search_car_rental tool or from get_coordinates tool.")
    pickup_time: str = Field(description="Pickup time in format YYYY-MM-DDTHH:MM:SS. Must be decided by you based on the pickup_instructions returned from search_car_rental tool and time used to call the tool.")
    cost: float = Field(description="Cost of the rental car in USD. Must be a valid cost estimate based on the price returned from search_car_rental tool.")
    vehicle: VehicleDetails = Field(description="Vehicle specifications. Must be a valid vehicle specifications returned from search_car_rental tool.")
    pickup_tips: str = Field(description="Tips for the rental car pickup. Must be generated by you based on the rental car company name and vehicle name and any results you get from search_web tool.")
    booking_url: str = Field(description="URL to book the rental car. Must be a valid booking URL returned from search_car_rental tool.")

class CarDropoffEventDetails(BaseModel):
    rental_company_name: str = Field(description="Name of the rental car company. Must be a valid supplier name returned from search_car_rental tool.")
    rental_company_logo_url: Optional[str] = Field(default=None, description="Logo URL of the rental car company. Must be a valid supplier logo URL returned from search_car_rental tool.")
    dropoff_instructions: str = Field(description="Instructions for dropoff. Must be a valid dropoff instructions returned from search_car_rental tool.")
    dropoff_location_id: str = Field(description="Dropoff location ID. Must be a valid dropoff location ID returned from search_car_rental tool.")
    dropoff_location_name: str = Field(description="Dropoff location name. Must be a valid dropoff location name returned from search_car_rental tool.")
    dropoff_location_address: str = Field(description="Dropoff location address. Must be a valid dropoff location address returned from search_car_rental tool.")
    dropoff_location_coordinates: Coordinates = Field(description="Coordinates of the dropoff location. Must be a valid dropoff location coordinates returned from search_car_rental tool or from get_coordinates tool.")
    dropoff_time: str = Field(description="Dropoff time in format YYYY-MM-DDTHH:MM:SS. Must be decided by you based on the dropoff_instructions returned from search_car_rental tool and time used to call the tool.")
    dropoff_tips: str = Field(description="Tips for the rental car dropoff. Must be generated by you based on the rental car company name and vehicle name and any results you get from search_web tool.")
    
class PlaceEventDetails(BaseModel):
    event_name: str = Field(description="Give a name to the event. Must be generated by you based on the place name and type of the place and activity you are planning.")
    event_description: str = Field(description="Give a description to the event. Must be generated by you based on the place name and type of the place and activity you are planning.")
    event_tips: str = Field(description="Tips for the event. Must be generated by you based on the place name and type of the place and activity you are planning or from search_web tool.")
    place_name: str = Field(description="Name of the restaurant or activity location. Must be a valid place name returned from search_places or search_places_nearby tool.")
    place_id: str = Field(description="Google Place ID. Must be a valid Google Place ID returned from search_places or search_places_nearby tool.")
    address: str = Field(description="Formatted address. Must be a valid address returned from search_places or search_places_nearby tool.")
    coordinates: Coordinates = Field(description="Coordinates of the place. Must be a valid coordinates returned from search_places or search_places_nearby tool or from get_coordinates tool.")
    summary: str = Field(description="Editorial or Generative summary of the place. Must be one of the valid summaries returned from search_places or search_places_nearby tool or from search_web tool. Or it can be a generated summary by you based on the place name and type of the place and activity you are planning.")
    rating: Optional[float] = Field(default=None, description="Rating of the place. Must be a valid rating returned from search_places or search_places_nearby tool.")
    price_level: str = Field(description="Price level string. Must be a valid price level string returned from search_places or search_places_nearby tool.")
    cost: float = Field(description="Cost of the activity in USD. Must be a valid cost estimate based on priceRange and priceLevel returned from search_places or search_places_nearby tool. The cost estimate must be returned taking in account the number of travellers and the duration of the activity.")
    start_time: str = Field(description="Start time in format YYYY-MM-DDTHH:MM:SS.")
    end_time: str = Field(description="End time in format YYYY-MM-DDTHH:MM:SS")
    durationMinutes: float = Field(description="Duration of the activity in minutes.")
    google_maps_url: str = Field(description="Google Maps URL. Must be a valid Google Maps URL returned from search_places or search_places_nearby tool.")
    website_url: str = Field(description="Website URL of the place. Must be a valid website URL returned from search_places or search_places_nearby tool.")

class CommuteEventDetails(BaseModel):
    originName: str = Field(description="Commute origin address/location. Must be a valid address or place name returned from search_places or search_places_nearby tool.")
    destinationName: str = Field(description="Commute destination address/location. Must be a valid address or place name returned from search_places or search_places_nearby tool.")
    origin_coordinates: Coordinates = Field(description="Coordinates of the true origin. Must be a valid coordinates returned from search_places or search_places_nearby tool, or from get_coordinates tool.")
    destination_coordinates: Coordinates = Field(description="Coordinates of the destination. Must be a valid coordinates returned from search_places or search_places_nearby tool, or from get_coordinates tool.")
    travel_mode: Literal["DRIVE", "WALK", "BICYCLE", "TRANSIT", "TWO_WHEELER"] = Field(description="Mode of travel for the commute.")
    distanceMeters: float = Field(description="Distance in meters. Must be a valid distance returned from get_route or get_route_matrix tool.")
    durationSeconds: float = Field(description="Duration of the commute in seconds. Must be a valid duration returned from get_route or get_route_matrix tool.")
    commute_tips: str = Field(description="Tips for the commute. Must be valid tips either from warnings from get_route or get_route_matrix tool, or from search_web tool.")
    transit_fare: Optional[float] = Field(default=None, description="Fare cost if travel mode is TRANSIT. Must be a valid fare cost returned from get_route or get_route_matrix tool. The cost returned is for 1 traveller, so if you are planning for multiple travellers, you need to multiply the cost by the number of travellers.")
    polyline: str = Field(description="Polyline of the route. Must be a valid polyline returned from get_route or get_route_matrix tool.")
    maps_url: str = Field(description="Google Maps route URL. Must be a valid Google Maps route URL returned from get_route or get_route_matrix tool.")

class OtherEventDetails(BaseModel):
    event_name: str = Field(description="Give a name to the event. Must be generated by you based on the place name and type of the place and activity you are planning.")
    event_description: str = Field(description="Give a description to the event. Must be generated by you based on the place name and type of the place and activity you are planning.")
    event_tips: str = Field(description="Tips for the event. Must be generated by you based on the place name and type of the place and activity you are planning or from search_web tool.")
    location: str = Field(description="Location of the event. Must be a valid location name.")
    address: str = Field(description="Formatted address. Must be a valid address for the event location returned from search_places or search_places_nearby tool or from search_web tool.")
    coordinates: Coordinates = Field(description="Coordinates of the place. Must be a valid coordinates returned from search_places or search_places_nearby tool or from get_coordinates tool.")
    summary: str = Field(description="Editorial or Generative summary of the place. Must be one of the valid summaries returned from search_places or search_places_nearby tool or from search_web tool. Or it can be a generated summary by you based on the place name and type of the place and activity you are planning.")
    cost: float = Field(description="Cost of the activity in USD. Must be a valid cost estimate for the event. The cost estimate must be returned taking in account the number of travellers and the duration of the activity.")
    start_time: str = Field(description="Start time in format YYYY-MM-DDTHH:MM:SS.")
    end_time: str = Field(description="End time in format YYYY-MM-DDTHH:MM:SS")
    durationMinutes: float = Field(description="Duration of the activity in minutes.")
    google_maps_url: str = Field(description="Google Maps URL. Must be a valid Google Maps URL returned from search_places or search_places_nearby tool.")
    website_url: str = Field(description="Website URL of the place. Must be a valid website URL returned from search_places or search_places_nearby tool.")

# Trip End Event Details
class EndEventDetails(BaseModel):
    trip_title: str = Field(description="Regenerate the trip title based on the results from all the tools, trip planned and time of the trip.")
    trip_cost: float = Field(description="Total cost for the entire trip in USD. Calculate this based on the cost of all the events in the itinerary and on the basis of estimated costs for the events with no cost provided and the number of travellers and the duration of the trip.")
    trip_tips: List[str] = Field(description="Helpful travel tips for the user for the trip planned. Must be generated by you based on the results from all the tools, trip planned, time of the trip, weather conditions and results you get from search_web tool.")

class AddItineraryEvent(BaseModel):
    day_number: int = Field(
        description="The chronological day number of the trip starting from 1 for the first day and ending with the last day except for the START and END events. For START event use 0 and for END event use -1 for the day number. This is used to identify the day of the trip."
    )
    day_title: str = Field(description="A small title for the day in format `Day <day_number> - <title>`. Must be generated by you based on the day number and the start date of the trip. Use `Start` for the title of the START event and `End` for the title of the END event. Update this title for each day as you go along the itinerary for the day.")
    date: str = Field(description="Date of the event in format YYYY-MM-DD. Calculate this based on the day number and the start date of the trip. Use `Start` for the date of the START event and `End` for the date of the END event.")
    event_number: int = Field(
        description="The sequential event number for the day starting from 1 for the first event and ending with the last event except for the START and END events. Ordered chronologically. For START event use 0 and for END event use -1 for the event number. This is used to identify the event of the day."
    )
    event_type: EventTypes = Field(
        description="The specific type of the event. Must be START first, then others, and strictly END as the final event."
    )
    start_details: Optional[StartEventDetails] = Field(default=None, description="Populate this only if event_type is START. Never populate for any other event type.")
    flight_takeoff_details: Optional[FlightTakeoffEventDetails] = Field(default=None, description="Populate this only if event_type is FLIGHT_TAKEOFF. Never populate for any other event type.")
    flight_land_details: Optional[FlightLandEventDetails] = Field(default=None, description="Populate this only if event_type is FLIGHT_LAND. Never populate for any other event type.")
    hotel_checkin_details: Optional[HotelCheckinEventDetails] = Field(default=None, description="Populate this only if event_type is HOTEL_CHECKIN. Never populate for any other event type.")
    hotel_checkout_details: Optional[HotelCheckoutEventDetails] = Field(default=None, description="Populate this only if event_type is HOTEL_CHECKOUT. Never populate for any other event type.")
    car_pickup_details: Optional[CarPickupEventDetails] = Field(default=None, description="Populate this only if event_type is CAR_PICKUP. Never populate for any other event type.")
    car_dropoff_details: Optional[CarDropoffEventDetails] = Field(default=None, description="Populate this only if event_type is CAR_DROPOFF. Never populate for any other event type.")
    place_details: Optional[PlaceEventDetails] = Field(default=None, description="Populate this only if event_type is DINING or ACTIVITY. Never populate for any other event type.")
    commute_details: Optional[CommuteEventDetails] = Field(default=None, description="Populate this only if event_type is COMMUTE. Never populate for any other event type.")
    other_details: Optional[OtherEventDetails] = Field(default=None, description="Populate this only if event_type is OTHER. Never populate for any other event type.")
    end_details: Optional[EndEventDetails] = Field(default=None, description="Populate this only if event_type is END. Never populate for any other event type.")
