# database/models/tripsTable.py

"""
This file contains the models for the trips table.
"""

from sqlalchemy import Column, Index, String, DateTime, Boolean, Enum, Integer, ForeignKey
from sqlalchemy.dialects.postgresql import UUID, JSONB, ARRAY
from sqlalchemy.orm import relationship
from app.database.database import Base
from sqlalchemy.sql import func
import uuid
import enum

class PlanningType(str, enum.Enum):
    SOLO = "solo"
    GROUP = "squad"

class RoutingStyle(str, enum.Enum):
    SINGLE_HUB = "single-hub"
    MULTI_HOP = "multi-hop"

class TripStatus(str, enum.Enum):
    DRAFT = "draft" # The trip is in draft status and may or may not be ready to be generated by the AI Agent.
    GENERATING = "generating" # The trip is in generating status and is being generated by the AI Agent.
    UPCOMING = "upcoming" # The trip is in upcoming status and is upcoming. The generated itinerary is ready to be used.
    ACTIVE = "active" # The trip is in active status and is currently ongoing. The generated itinerary is ready to be used.
    COMPLETED = "completed" # The trip is in completed status and is completed. The generated itinerary is ready to be used.
    CANCELLED = "cancelled" # The trip is in cancelled status and is cancelled. The generated itinerary is not ready to be used.

class Trip(Base):
    __tablename__ = "trips"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, nullable=False, index=True)
    owner_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False, index=True)

    planning_type = Column(Enum(PlanningType), nullable=False)
    routing_style = Column(Enum(RoutingStyle), nullable=False)

    origin = Column(JSONB, nullable=False)
    destinations = Column(ARRAY(JSONB), nullable=False)
    start_date = Column(JSONB, nullable=False)
    end_date = Column(JSONB, nullable=False)
    pace = Column(String, nullable=False)
    budget = Column(String, nullable=False)
    conversational_context = Column(String, nullable=False)

    adults = Column(Integer, nullable=False)
    children = Column(Integer, nullable=False)

    trip_status = Column(Enum(TripStatus), nullable=False)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    members = relationship("TripMember", back_populates="trip", cascade="all, delete-orphan")
    owner = relationship("User", back_populates="owned_trips")