import LegalPage from './LegalPage';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-base font-semibold text-white mb-3">{title}</h2>
      <div className="space-y-3">{children}</div>
    </section>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <p className="text-white/65 text-sm leading-relaxed">{children}</p>;
}

function Ul({ items }: { items: string[] }) {
  return (
    <ul className="list-none space-y-1.5 pl-0">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2 text-white/65 text-sm">
          <span className="mt-1.5 w-1 h-1 rounded-full bg-cyan/60 flex-shrink-0" />
          {item}
        </li>
      ))}
    </ul>
  );
}

export default function TermsOfService() {
  return (
    <LegalPage title="Terms of Service" lastUpdated="May 3, 2026">
      <Section title="1. Acceptance of Terms">
        <P>
          By accessing or using BonPlan.ai ("Service", "we", "us"), you agree to be bound by these Terms of Service ("Terms").
          If you do not agree, do not use the Service.
        </P>
        <P>
          These Terms apply to all users including registered account holders, visitors, and collaborators on shared trips.
          We may update these Terms at any time; continued use after changes constitutes acceptance.
        </P>
      </Section>

      <Section title="2. Description of Service">
        <P>
          BonPlan.ai is an AI-powered travel itinerary planning platform. It allows users to generate, edit, and share
          personalised trip plans using artificial intelligence. The Service includes solo planning, collaborative group
          planning, itinerary export, and account management features.
        </P>
        <P>
          The Service is provided "as is" and is subject to availability. We reserve the right to modify, suspend, or
          discontinue any part of the Service at any time with reasonable notice.
        </P>
      </Section>

      <Section title="3. Eligibility & Accounts">
        <P>
          You must be at least 13 years old to create an account. By registering, you represent that you meet this requirement.
        </P>
        <P>You are responsible for:</P>
        <Ul items={[
          'Maintaining the confidentiality of your account credentials.',
          'All activity that occurs under your account.',
          'Notifying us immediately of any unauthorised access at support@bonplan.ai.',
        ]} />
        <P>
          We reserve the right to suspend or terminate accounts that violate these Terms or that have been inactive for an
          extended period.
        </P>
      </Section>

      <Section title="4. Acceptable Use">
        <P>You agree not to:</P>
        <Ul items={[
          'Use the Service for any unlawful purpose or in violation of any applicable law or regulation.',
          'Attempt to circumvent rate limits, quotas, or access controls through automated requests, scraping, or exploiting API endpoints.',
          'Reverse engineer, decompile, or attempt to extract the source code of BonPlan.ai.',
          'Impersonate any person or entity or misrepresent your affiliation with any person or entity.',
          'Upload or transmit malicious code, viruses, or any content that could harm the Service or other users.',
          'Use the Service to generate content that is illegal, hateful, harassing, or violates the rights of others.',
          'Resell, sublicense, or commercially exploit the Service without our written consent.',
        ]} />
        <P>
          Violation of these terms may result in immediate account suspension without refund or notice.
        </P>
      </Section>

      <Section title="5. AI-Generated Content Disclaimer">
        <P>
          BonPlan.ai uses large language models (including Google Gemini) to generate travel itineraries. You acknowledge that:
        </P>
        <Ul items={[
          'AI-generated itineraries are suggestions only and may contain errors, outdated information, or inaccuracies.',
          'We do not guarantee the accuracy, completeness, or suitability of any generated plan for your specific needs.',
          'Travel conditions, prices, availability, visa requirements, and safety situations change constantly. Always verify critical details independently before travelling.',
          'BonPlan.ai is not a licensed travel agent. Nothing on this platform constitutes professional travel advice.',
          'You are solely responsible for all decisions made based on content generated by the Service.',
        ]} />
      </Section>

      <Section title="6. Intellectual Property">
        <P>
          The BonPlan.ai platform, including its design, code, branding, and AI models, is owned by us and protected by
          applicable intellectual property laws.
        </P>
        <P>
          Trip itineraries and content you generate using the Service are yours. You grant us a non-exclusive, royalty-free
          licence to store and process that content solely for the purpose of providing the Service to you. We do not claim
          ownership over your trip data.
        </P>
        <P>
          You may not reproduce, distribute, or create derivative works from BonPlan.ai's platform or branding without
          explicit written permission.
        </P>
      </Section>

      <Section title="7. Rate Limits & Fair Use">
        <P>
          To ensure fair access for all users, BonPlan.ai enforces per-user rate limits on AI generation and other
          resource-intensive features. These limits are displayed within the platform and may change over time.
        </P>
        <P>
          Attempting to circumvent rate limits — including through multiple accounts, automated tools, or API abuse — is a
          violation of these Terms and may result in permanent account suspension.
        </P>
      </Section>

      <Section title="8. Limitation of Liability">
        <P>
          To the maximum extent permitted by law, BonPlan.ai and its operators shall not be liable for:
        </P>
        <Ul items={[
          'Any indirect, incidental, special, consequential, or punitive damages.',
          'Loss of data, revenue, profits, or business opportunities.',
          'Damages arising from reliance on AI-generated itinerary content.',
          'Service interruptions, downtime, or data loss.',
          'Actions of third-party services integrated into the platform (Google, airlines, hotels, etc.).',
        ]} />
        <P>
          Our total liability to you for any claim arising from use of the Service shall not exceed the amount you paid us
          in the 12 months preceding the claim, or €50, whichever is greater.
        </P>
      </Section>

      <Section title="9. Indemnification">
        <P>
          You agree to indemnify and hold harmless BonPlan.ai and its operators from any claims, damages, losses, or expenses
          (including legal fees) arising from your use of the Service, your violation of these Terms, or your violation of
          any third-party rights.
        </P>
      </Section>

      <Section title="10. Governing Law">
        <P>
          These Terms are governed by and construed in accordance with applicable law. Any disputes arising from these Terms
          or your use of the Service shall be subject to the exclusive jurisdiction of the competent courts.
        </P>
      </Section>

      <Section title="11. Termination">
        <P>
          You may delete your account at any time through the account settings page. We may suspend or terminate your access
          at any time for violation of these Terms or for any other reason at our discretion.
        </P>
        <P>
          Upon termination, your right to use the Service ceases immediately. Sections 5, 6, 8, and 9 survive termination.
        </P>
      </Section>

      <Section title="12. Changes to These Terms">
        <P>
          We may revise these Terms at any time. We will update the "Last updated" date at the top of this page. For material
          changes, we may notify you via email or an in-app notice. Continued use of the Service after changes constitutes
          your acceptance of the revised Terms.
        </P>
      </Section>

      <Section title="13. Contact">
        <P>
          Questions about these Terms?{' '}
          <a href="mailto:support@bonplan.ai" className="text-cyan hover:underline">
            support@bonplan.ai
          </a>
        </P>
      </Section>
    </LegalPage>
  );
}
