"""updated events to be mutable lists

Revision ID: 7ec6c2104fa6
Revises: ce1dcc40319e
Create Date: 2026-04-17 15:44:52.557729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec6c2104fa6'
down_revision: Union[str, Sequence[str], None] = 'ce1dcc40319e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
