"""Updated

Revision ID: b565e513b7d4
Revises: f4fcf7724dfa
Create Date: 2026-05-09 22:32:38.087990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b565e513b7d4'
down_revision: Union[str, Sequence[str], None] = 'f4fcf7724dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place_photo_cache', 'image_data',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('place_photo_cache', 'r2_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_unique_constraint('uq_snapshot_trip_version', 'trip_itinerary_snapshots', ['trip_id', 'version_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_snapshot_trip_version', 'trip_itinerary_snapshots', type_='unique')
    op.alter_column('place_photo_cache', 'r2_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('place_photo_cache', 'image_data',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
